config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'products#index'

  namespace :users do
    root to: "products#index"
  end

  get '/profile', to: 'profiles#profile'

  resources :products do
    resources :rentals, only: [:create]
  end
  resources :rentals, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :rentals, dependent: :destroy
  has_many_attached :photos

  validates :name, presence: true, uniqueness: true
  validates :capacity, :price, :place, presence: true

  include PgSearch::Model
  pg_search_scope :search_product,
    against: [ :name, :description, :place, :price ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :departure_date, :arrival_date, presence: true
  validate :no_past_booking
  validate :overlaps

  def no_past_booking
    if Date.today > arrival_date.to_date
      errors.add(:arrival_date, "Cannot be in the past")
    elsif Date.today > departure_date.to_date
      errors.add(:departure_date, "Cannot be in the past")
    end
  end

  def overlaps
    rentals = Rental.where(product_id: product_id)
    rentals.each do |rental|
      if arrival_date <= rental.departure_date && rental.arrival_date <= departure_date
        return errors.add(:arrival_date, "Already booked")
      end
    end
  end

  def total_price
    total = departure_date - arrival_date
    return total.to_i * self.product.price
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :rentals, dependent: :destroy

  has_many :demands, through: :products, source: :rentals

  validates :first_name, :last_name, :date_of_birth, presence: true
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit::Authorization
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def after_update_path_for(resource)
    redirect_to profile_path
  end

  private

  def configure_permitted_parameters
    attributes = [:first_name, :last_name, :date_of_birth, :photo]
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

  def skip_pundit?
    devise_controller?
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :destroy, :update]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @products = policy_scope(Product)

    if params[:query].present?
      # raise
      @products = @products.search_product(params[:query])
    end
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    authorize @product

    if @product.save
      redirect_to product_path(@product)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @product
  end

  def update
    authorize @product
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def show
    @rental = Rental.new
    authorize @product
  end

  def destroy
    authorize @product
    @product.destroy
    redirect_to products_path, status: :see_other
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :capacity, :description, :price, :place, :genre_id, photos: [])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def profile
    @products = current_user.products
    authorize @products
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    @rental.product = @product
    authorize @rental

    if @rental.save
      redirect_to profile_path
      flash.alert = "Booking OK"
    else
      render template: "products/show", status: :unprocessable_entity
    end
  end

  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy
    redirect_to profile_path
    authorize @rental
  end

  private

  def rental_params
    params.require(:rental).permit(:arrival_date, :departure_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SPACEBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="icon" type="image/x-icon" href="https://res.cloudinary.com/dryhvwfvf/image/upload/v1653640498/development/11wd9edxu6xyvnf4heny5mvrin0w.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/navbar"  %>

    <div class="container-footer">
      <%= yield %>
    </div>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/products/_searchbar.html.erb
<%= form_tag products_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a place in the milky-way"
  %>
  <%= submit_tag "Search", class: "button-white" %>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <div class="form">
  <h2>Edit your place :</h2>
    <div>
      <% if policy(@product).edit? %>
        <%= simple_form_for(@product) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :capacity %>
        <%= f.input :price %>
        <%= f.input :place %>
        <%= f.association :genre, collection: Genre.all.order(:name), prompt: "Choose a genre" %>
        <%= f.submit class:"button-orange" %>
        <% end %>
      <% end %>
   </div>

    <div class="form-sup-link">
      <%= link_to "<<", :back, class:"button-white" %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
  <%# <div  style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images2.alphacoders.com/542/thumb-1920-542730.png);">
      <p>For you next holiday destination, aim for the stars!</p>
  </div> %>
<div id="carouselExampleControls" class="carousel slide banner" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://res.cloudinary.com/dryhvwfvf/image/upload/v1653642605/development/banner-marsa-attack_jst6bl.png" class="d-block w-100" alt="banner-mars-attack">
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/dryhvwfvf/image/upload/v1653642606/development/banner-spaceship_bq8rih.png" class="d-block w-100" alt="banner-valentins-day">
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/dryhvwfvf/image/upload/v1653642605/development/banner-saturn_buvrms.png" class="d-block w-100" alt="banner-spring-break">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="container-home-page">
  <div class="container-search-bar">
    <div class="search-bar col-6">
      <%= render "searchbar", product: @product %>
    </div>
  </div>
    <div class="cards">
    <% @products.each do |product| %>
      <div class="card card-index">
        <%= link_to product_path(product) do %>
          <i class="fa-solid fa-heart" style="color: white"></i>
          <div class="card-img">

          <% if product.photos.present? %>
          <%# START CARROUSEL %>
            <div id="carouselExampleDark-<%=product.id%>" class="carousel carousel-dark slide m-0 p-0"> <%#data-bs-ride="carousel"%>
              <div class="carousel-inner">
                  <% product.photos.each_with_index do |photo, index| %>
                    <div class="carousel-item <%="active" if index == 0%>"> <%#data-bs-interval="2000"%>
                      <%= cl_image_tag photo.key, height: 257, width: 386, crop: :fill, class: "d-block w-100" %>
                      <div class="carousel-caption d-none d-md-block">
                      </div>
                    </div>
                  <% end %>
              </div>
              <% if product.photos.length > 1 %>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark-<%=product.id%>" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark-<%=product.id%>" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              <% end %>
            </div>
          <% else %>
              <img src="https://source.unsplash.com/random/350x253/?espace" alt="image card">
          <% end %>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>

          </div>


          <div class="card-body">
            <div class="card-text">
            <p class="card-title"><%= product.name %></p>
            <p class="card-description"><%= product.description %></p>
            </div>
            <div class="card-price">
              <p><%= product.price %>€/night</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="form">
    <h2>Add a new place :</h2>
    <div>
      <%= simple_form_for @product do |f| %>
      <%= f.input :name %>
      <%= f.input :capacity %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :place %>
      <%= f.association :genre, collection: Genre.all.order(:name), prompt: "Choose a genre" %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit class:"button-orange" %>
      <% end %>
    </div>

    <div class="form-sup-link">
      <%= link_to "<<", :back, class:"button-white" %>
    </div>

  </div>
</div>

app/views/products/show.html.erb
<div class="container">

  <div class="tabs">
    <h2><%= @product.name %></h1>
    <p><%= @product.place %><p>
    <% if policy(@product).edit? %>
    <%= link_to "+", product_path(@product), class:"button-white", id:"delete", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  <% end %>
  </div>

  <div class="carousel">
    <figure>
      <% @product.photos.each do |photo| %>
        <%= cl_image_tag photo.key, height: 253, width: 350, crop: :fill %>
      <% end %>
    </figure>

    <nav>
      <button class="button-white">>></button>
    </nav>
  </div>

  <div class="tabs-information">
    <div id="description">
      <h2><%= @product.place %><h2>
      <p><%= @product.capacity %> rooms<p>
      <p><%= @product.description %></p>
    </div>

    <div id="reservation">
      <p style="font-wize: light;"><%= @product.price %> €/night<p>

      <div id="reservation-detail" data-controller="flatpickr" data-flatpickr-price-value='<%= @product.price %>'>
        <%= simple_form_for [@product, @rental] do |f| %>
          <div class="d-flex" style="width: 450px; margin: 0 auto;">
            <div id="arrival">
              <span>Arrival</span>
              <p><%= f.input :arrival_date, label: false, as: :string, required: false, input_html: { class: "datepicker", data: { flatpickr_target: "startDate",  action: 'input->flatpickr#result' } }%></p>
            </div>

            <div id="departure">
              <span>Departure</span>
              <p><%= f.input :departure_date, label: false, as: :string, required: false, input_html: { class: "datepicker", data: { flatpickr_target: "endDate",  action: 'input->flatpickr#result' } } %></p>
            </div>
          </div>
          <div id="reservation-result">
            <span data-flatpickr-target="result"></span>
          </div>
          <% if user_signed_in? %>
            <%= f.submit "Reservation", class:"button-orange"%>
          <% else %>
            <div data-controller="alert">
              <%= f.submit "Reservation", class:"button-orange", data: { alert_target: 'button', action: 'click->alert#notice' } %>
              <span data-alert-target="notice"></span>
            </div>
          <% end %>
      <% end %>
    </div>

      <%# nombre de nuit/price par nuit%>
      <%# TOTAL%>
    </div>
  </div>

  <%= link_to "<<", products_path, class:"button-white" %>
  <% if policy(@product).edit? %>
    <%= link_to "Edit", edit_product_path(@product.id), class:"button-white" %>
  <% end %>
</div>



<script>
  var
    carousel = document.querySelector('.carousel'),
    figure = carousel.querySelector('figure'),
    nav = carousel.querySelector('nav'),
    numImages = figure.childElementCount,
    theta =  2 * Math.PI / numImages,
    currImage = 0
  ;

  nav.addEventListener('click', onClick, true);

  function onClick(e) {
    e.stopPropagation();

    var t = e.target;
    if (t.tagName.toUpperCase() != 'BUTTON')
      return;

    if (t.classList.contains('next')) {
      currImage++;
    }
    else {
      currImage--;
    }

    figure.style.transform = `rotateY(${currImage * -theta}rad)`;
  }
</script>

app/views/profiles/profile.html.erb
<%= render "shared/navbar" %>

<div class= "main-container">

  <div class="profile">
    <h2>My profile</h2>
    <div id="profile-img">
      <%= cl_image_tag current_user.photo.key %>
    </div>
    <div class="profile-text">
      <h4><%= current_user.first_name%> <%= current_user.last_name%></h4>
      <h5><i class="fa-solid fa-envelope"></i> <%= current_user.email%></h5>
      <h5><i class="fa-solid fa-cake-candles"></i> <%= current_user.date_of_birth%></h5>
    </div>
    <div>
      <%= link_to "Modify", edit_user_registration_path(@current_user), class:"button-white"%>
    </div>
  </div>

  <div class="products-wrapper">
    <h2>My places</h2>
    <div class="products">
      <% current_user.products.each do |product| %>
        <div class="product-card">
          <div class="product-card-booking-name">
            <p><%= product.name %></p>
          </div>
          <%= cl_image_tag product.photos.first.key, crop: :fill %>
          <div>
            <div class="product-card-infos">
              <p>Located in: <%= product.place %></p>
              <p>Capacity : <%= product.capacity %></p>
              <p><%= product.price %>$</p>
            </div>
            <div id="product-card-infos-link">
              <%= link_to edit_product_path(product) do %>
                <i class="fa-solid fa-pencil button-white"></i>
              <% end %>
              <%= link_to product_path(product), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                <i class="fa-solid fa-trash button-white"></i>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>

        <%= link_to new_product_path do %>
          <div id="product-card-new">
              <p>Add a new place</p>
              <h3>+</h3>
          </div>
        <% end %>
    </div>

    <div>
      <h2>My bookings</h2>
      <div class="products">
        <% current_user.rentals.each do |rental| %>
          <div class="product-card">
            <p class="product-card-booking-name"><%= rental.product.name %></p>
            <div id="product-card-booking-date">
              <p>From : <%= rental.arrival_date %></p>
              <p>Until : <%= rental.departure_date %></p>
              <p>Price : <%= rental.total_price %>€</p>
            </div>
            <%= link_to "Cancel my booking", rental_path(rental), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"button-orange" %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer" style="background-image: linear-gradient(rgba(0, 0, 0, 0.403), rgba(0, 0, 0, 0.403)), url(<%= asset_path("footer/footer-background.jpg") %>)">
  <div class="footer-logo">
    <%= image_tag "logos/logo2-white.png" %>
  </div>
  <div class="footer-slogan">
    <p>To infinity & beyond !</p>
  </div>
  <div class="footer-links">
    <a href="https://www.youtube.com/spacex" target="_blank"><%= image_tag "links/saturn.png" %></a>
    <a href="https://www.instagram.com/spacex/" target="_blank"><%= image_tag "links/outer-space-alien.png" %></a>
    <a href="https://twitter.com/spacex" target="_blank"><%= image_tag "links/arcade-game.png" %></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top"
  data-controller="navbar"
  data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to root_path,  class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/alk1805/image/upload/v1653488994/Space-bnb_-_logo_1_xovdrm.png" %>
    <% end %>
      <h1 id= "main-title">SpaceBnB</h1>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, class: "button-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>